import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';

const DB_FILE = path.join(process.cwd(), 'server', 'database', 'db.json');

export interface User {
  id: string;
  name: string;
  email: string;
  passwordHash: string;
  isAdmin: boolean;
  createdAt: string;
}

export interface Budget {
  id: string;
  userId: string;
  monthlyIncome: number;
  fixedExpenses: number; // calculated from additions or initial
  variableExpenses: number;
  budgetLimit: number;
  recommendedBudget: number; // generated by AI
  remainingAmount: number;
  createdAt: string;
}

export interface SavingsGoal {
  id: string;
  userId: string;
  goalName: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string;
  createdAt: string;
}

export interface Expense {
  id: string;
  userId: string;
  title: string;
  category: string;
  amount: number;
  date: string;
}

export interface Income {
  id: string;
  userId: string;
  source: string;
  amount: number;
  date: string;
}

export interface AIRecommendation {
  id: string;
  userId: string;
  recommendation: string; // Markdown recommendation content
  priority: 'High' | 'Medium' | 'Low';
  type: 'budget' | 'expense' | 'savings' | 'health';
  createdAt: string;
}

export interface Notification {
  id: string;
  userId: string;
  message: string;
  type: 'budget_exceeded' | 'bill_reminder' | 'savings_reminder' | 'goal_completed' | 'report_ready';
  read: boolean;
  createdAt: string;
}

interface DatabaseSchema {
  users: User[];
  budgets: Budget[];
  savingsGoals: SavingsGoal[];
  expenses: Expense[];
  incomes: Income[];
  aiRecommendations: AIRecommendation[];
  notifications: Notification[];
}

class Database {
  private data: DatabaseSchema = {
    users: [],
    budgets: [],
    savingsGoals: [],
    expenses: [],
    incomes: [],
    aiRecommendations: [],
    notifications: [],
  };

  constructor() {
    this.init();
  }

  private init() {
    const dir = path.dirname(DB_FILE);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    if (fs.existsSync(DB_FILE)) {
      try {
        const fileContent = fs.readFileSync(DB_FILE, 'utf-8');
        this.data = JSON.parse(fileContent);
      } catch (e) {
        console.error('Error reading database, resetting database...', e);
        this.resetToDefaults();
      }
    } else {
      this.resetToDefaults();
    }
  }

  private resetToDefaults() {
    // Hash default admin password
    const salt = bcrypt.genSaltSync(10);
    const adminPasswordHash = bcrypt.hashSync('adminpassword', salt);
    const testUserPasswordHash = bcrypt.hashSync('userpassword', salt);

    this.data = {
      users: [
        {
          id: 'admin-id',
          name: 'Administrator',
          email: 'admin@budgetagent.com',
          passwordHash: adminPasswordHash,
          isAdmin: true,
          createdAt: new Date().toISOString(),
        },
        {
          id: 'test-user-id',
          name: 'Test User',
          email: 'test@budgetagent.com',
          passwordHash: testUserPasswordHash,
          isAdmin: false,
          createdAt: new Date().toISOString(),
        }
      ],
      budgets: [
        {
          id: 'budget-1',
          userId: 'test-user-id',
          monthlyIncome: 5000,
          fixedExpenses: 1500,
          variableExpenses: 1000,
          budgetLimit: 4000,
          recommendedBudget: 3500,
          remainingAmount: 2500,
          createdAt: new Date().toISOString(),
        }
      ],
      savingsGoals: [
        {
          id: 'goal-1',
          userId: 'test-user-id',
          goalName: 'Emergency Fund',
          targetAmount: 10000,
          currentAmount: 3500,
          deadline: '2026-12-31',
          createdAt: new Date().toISOString(),
        }
      ],
      expenses: [
        { id: 'exp-1', userId: 'test-user-id', title: 'Apartment Rent', category: 'Rent', amount: 1200, date: '2026-07-01' },
        { id: 'exp-2', userId: 'test-user-id', title: 'Grocery Shopping', category: 'Food', amount: 150, date: '2026-07-02' },
        { id: 'exp-3', userId: 'test-user-id', title: 'Internet Bill', category: 'Utilities', amount: 80, date: '2026-07-03' },
        { id: 'exp-4', userId: 'test-user-id', title: 'Dining Out', category: 'Food', amount: 65, date: '2026-07-04' },
        { id: 'exp-5', userId: 'test-user-id', title: 'Netflix Subscription', category: 'Entertainment', amount: 20, date: '2026-07-05' }
      ],
      incomes: [
        { id: 'inc-1', userId: 'test-user-id', source: 'Monthly Salary', amount: 5000, date: '2026-07-01' }
      ],
      aiRecommendations: [
        {
          id: 'rec-1',
          userId: 'test-user-id',
          recommendation: 'Based on your recent transactions, your **Food & Dining** spending is slightly above your budget allocation. Consider preparing more meals at home to save roughly **$150/month**, which you could redirect to your **Emergency Fund** savings goal.',
          priority: 'Medium',
          type: 'expense',
          createdAt: new Date().toISOString()
        }
      ],
      notifications: [
        {
          id: 'notif-1',
          userId: 'test-user-id',
          message: 'Welcome to your Budget Planning Agent! Try entering your first budget or savings goals to get started.',
          type: 'report_ready',
          read: false,
          createdAt: new Date().toISOString()
        }
      ],
    };
    this.save();
  }

  public save() {
    try {
      fs.writeFileSync(DB_FILE, JSON.stringify(this.data, null, 2), 'utf-8');
    } catch (e) {
      console.error('Failed to write to database file:', e);
    }
  }

  // Collection Accessors
  public get users() { return this.data.users; }
  public set users(val: User[]) { this.data.users = val; }
  public get budgets() { return this.data.budgets; }
  public set budgets(val: Budget[]) { this.data.budgets = val; }
  public get savingsGoals() { return this.data.savingsGoals; }
  public set savingsGoals(val: SavingsGoal[]) { this.data.savingsGoals = val; }
  public get expenses() { return this.data.expenses; }
  public set expenses(val: Expense[]) { this.data.expenses = val; }
  public get incomes() { return this.data.incomes; }
  public set incomes(val: Income[]) { this.data.incomes = val; }
  public get aiRecommendations() { return this.data.aiRecommendations; }
  public set aiRecommendations(val: AIRecommendation[]) { this.data.aiRecommendations = val; }
  public get notifications() { return this.data.notifications; }
  public set notifications(val: Notification[]) { this.data.notifications = val; }
}

export const db = new Database();
export default db;
